version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure
  backend:
    image: r1sen007/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db
    restart: on-failure
  frontend:
    image: r1sen007/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: r1sen007/kittygram_gateway
    env_file: .env
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
      - static:/static
      - media:/app/media/
    restart: on-failure
